version: '3.8'

services:
  commanav-logging:
    image: grt47/comma_nav_server:latest
    container_name: commanav_logger
    ports:
      - "5000:5000"
    volumes:
      - /volume1/docker/carrotpilot/commanav_server:/app
    restart: always
