version: '3.8'

services:
  carrotnavi-logging:
    build: .
    container_name: carrotnavi_logger
    ports:
      - "5000:5000"
    volumes:
      - /volume1/docker/carrotpilot/commanav_server:/app
    restart: always
