version: '3.8'

services:
  commanav-logging:
    image: grt47/comma_nav_server:latest
    container_name: commanav_logger
    ports:
      - "5000:5000"
    volumes:
      - /volume1/docker/carrotpilot/commanav_server:/app
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 --threads 4 --worker-class gthread --timeout 120 --keep-alive 5 app:app
    restart: always
